language: python
sudo: required
python:
  - "3.6"


install:
  - pip install -r requirements.txt

script:
  - python run.py

before_install:
  -  openssl aes-256-cbc -K $encrypted_040c7bfba308_key -iv $encrypted_040c7bfba308_iv -in token.pickle.enc -out token.pickle -d